### ***Análise simples de dados de funcionários***

In [1]:
#importando biblioteca
import pandas as pd

In [3]:
dados = pd.read_excel('/dados_empresa.xlsx')
#visualisando os primeiros dados
dados.head()

,ID,Nome,Departamento,Cargo,Salario,Data_Admissao,Cidade
0,1,Ana Souza,TI,Analista de Dados,5500,2022-03-15,São Paulo
1,2,Carlos Lima,Financeiro,Analista Financeiro,4800,2021-07-10,Rio de Janeiro
2,3,Mariana Alves,RH,Recrutadora,4200,2023-01-05,Belo Horizonte
3,4,João Pedro,TI,Desenvolvedor,6200,2020-11-20,São Paulo
4,5,Fernanda Costa,Marketing,Social Media,3900,2022-06-30,Curitiba

In [4]:
#informações gerais da tabela
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             10 non-null     int64
 1   Nome           10 non-null     object
 2   Departamento   10 non-null     object
 3   Cargo          10 non-null     object
 4   Salario        10 non-null     int64
 5   Data_Admissao  10 non-null     object
 6   Cidade         10 non-null     object
dtypes: int64(2), object(5)
memory usage: 692.0+ bytes

In [12]:
#media salarial por cidade
media = dados.groupby("Cidade")["Salario"].mean()
print(media)

Cidade
Belo Horizonte    4200.000000
Campinas          7500.000000
Curitiba          3900.000000
Porto Alegre      5300.000000
Recife            4100.000000
Rio de Janeiro    4800.000000
Salvador          4600.000000
São Paulo         5066.666667
Name: Salario, dtype: float64

In [15]:
#quantidade de funcionarios por departamento
dados['Departamento'].value_counts()

Departamento
TI            4
Financeiro    2
RH            2
Marketing     1
Vendas        1
Name: count, dtype: int64